# array of regular expression strings to match workflow names
# which should be watched by bot
workflowWithTests = [
    '.*e2e.*', # all workflows with sub-string "screenshot" in their names will be watched by bot
]

# array of RegExp strings to match images inside artifacts (by their path or file name)
# which shows difference between two screenshot and which will be added to bot report comment
screenshotsDiffsPaths = [
    '.*__diff_output__.*', # it is default cypress folder name into which snapshot diffs are put
]

# Regular expression string to match images inside artifacts (by their path or file name)
# which are created by new screenshot tests.
newScreenshotMark = '.*==new==.*'

# array of RegExp strings to match branch names which should be skipped by bot
branchesIgnore = ["^release/.*"]
