name: Auto Assign to Project(s)

on:
    issues:
        types: [labeled]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PROJECTS_BASE_URL: 'https://github.com/TinkoffCreditSystems/taiga-ui/projects'

    DOCS_PROJECT_ID: 2
    DOCS_LABEL_FOR_ASSIGN: 'documentation'

jobs:
    assign-one-project:
        runs-on: ubuntu-latest
        name: Assign to one project
        steps:
            - name: Assign issues to documentation project
              uses: srggrs/assign-one-project-github-action@1.3.0
              if: 'contains(github.event.issue.labels.*.name, ${{ env.DOCS_LABEL_FOR_ASSIGN }})'
              with:
                  project: '${{ env.PROJECTS_BASE_URL }}/${{ env.DOCS_PROJECT_ID }}'
