name: Auto assign

on:
  issues:
    types: [labeled]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROJECTS_BASE_URL: 'https://github.com/TinkoffCreditSystems/taiga-ui/projects'

jobs:
  assign-projects:
    runs-on: ubuntu-latest
    env:
      DOC_LABEL: 'documentation'
      DOC_PROJECT_ID: 2
      INFRA_LABEL: 'dev-infra'
      INFRA_PROJECT_ID: 3
    steps:
      - name: Assign issues to documentation project
        uses: srggrs/assign-one-project-github-action@1.3.0
        if: contains(github.event.issue.labels.*.name, env.DOC_LABEL)
        with:
          project: '${{ env.PROJECTS_BASE_URL }}/${{ env.DOC_PROJECT_ID }}'

      - name: Assign issues to infrastructure project
        uses: srggrs/assign-one-project-github-action@1.3.0
        if: contains(github.event.issue.labels.*.name, env.INFRA_LABEL)
        with:
          project: '${{ env.PROJECTS_BASE_URL }}/${{ env.INFRA_PROJECT_ID }}'

concurrency:
  group: assign-project-${{ github.head_ref }}
  cancel-in-progress: true
