name: ðŸ¤– Auto rebase from main branch

on:
  push:
    branches: [main]

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Autorebase from main branch
        uses: peter-evans/rebase@v2.0.1
        with:
          base: main
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          head: 'Tinkoff:*'
          include-labels: 'autorebase'
