name: ðŸ¤– Auto label
on:
  pull_request_review:
    types: [submitted]

jobs:
  label-when-approved:
    if: github.event.review.state == 'APPROVED'
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.62.24
      - uses: taiga-family/ci/actions/setup/variables@v1.62.24
      - uses: taiga-family/ci/actions/auto/label-when-approved@v1.62.24
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
