name: ðŸ¤– Auto assign
on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-author:
    name: PR author as an assignee
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Setup global variables
        uses: ./.github/actions/variables

      - name: Auto assign
        if: env.IS_OWNER_MODE == 'true'
        uses: toshimaru/auto-author-assign@v1.6.2
        with:
          repo-token: ${{ secrets.TINKOFF_BOT_PAT }}
