name: ðŸ¤– Auto update dependencies by Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 */2 * *' # At 11:00 PM, every 2 days

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.1.1
        with:
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: 'debug'
