name: Rebase all pull requests on push to the base branch

on:
    push:
        branches: [main]

jobs:
    rebase:
        runs-on: ubuntu-latest
        steps:
            - name: Autorebase
              continue-on-error: true
              uses: peter-evans/rebase@v1.0.5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: main

concurrency:
    group: autorebase-${{ github.head_ref }}
    cancel-in-progress: true
