name: ðŸ¤– Auto assign

on:
  pull_request:
    types: [opened, reopened]

env:
  IS_FORK: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
  IS_DEPENDABOT: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}

jobs:
  assign-author:
    name: PR author as an assignee
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.3.7
        if: ${{ env.IS_FORK == 'false' && env.IS_DEPENDABOT == 'false' }}
        with:
          repo-token: ${{ secrets.TINKOFF_BOT_PAT }}
