name: ðŸ¤– Auto label
on: pull_request_review

jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.5.1

      - name: Label when approved
        if: env.IS_OWNER_MODE == 'true'
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: '2'
          ADD_LABEL: 'ready to merge'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
