name: ðŸ¤– Auto update dependencies by Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2,4' # At UTC 00:00 (MSK 03:00) on Tuesday and Thursday

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          configurationFile: default.json
        env:
          LOG_LEVEL: 'debug'
