name: ðŸ¤– Auto approve validation
on: pull_request

env:
  JOBS_NAME: '[ "Build packages", "Firebase", "Lint", "Collect coverage", "E2E result" ]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.25.8
      - uses: taiga-family/ci/actions/setup/variables@v1.25.8
      - id: matrix
        if: env.TAIGA_FAMILY_BOT_IS_AUTHOR == 'true'
        run: echo "value=$JOBS_NAME" >> $GITHUB_OUTPUT

  wait:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: taiga-family/ci/actions/run/wait-job@v1.25.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job: ${{ matrix.value }}

  approve:
    needs: [wait]
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/auto/approve/double@v1.25.8
        with:
          token1: ${{ secrets.GITHUB_TOKEN }}
          token2: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
      - uses: taiga-family/ci/actions/run/merge@v1.25.8
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: auto-approve-${{ github.head_ref }}
  cancel-in-progress: true
