name: Bundle size check

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build_and_check:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Bundlemon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: npx nx build

      - name: Run BundleMon
        run: npx bundlemon
        env:
          CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}}
