name: ⚙️ Bundle size
on:
  push:
    branches: [main]
  pull_request:

jobs:
  tracking:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.55.12
      - uses: taiga-family/ci/actions/setup/variables@v1.55.12
      - uses: taiga-family/ci/actions/setup/node@v1.55.12
      - run: npx nx prerender demo
      - run: npx --yes bundlemon --config .github/.bundlemonrc.json
        continue-on-error: true
        env:
          CI_COMMIT_SHA: ${{ env.CI_COMMIT_SHA }}
