name: ⚙️ Bundle size
on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  tracking:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.5.1
      - uses: taiga-family/ci/actions/setup-node@1.5.1

      - run: npx nx build demo

      - name: Run BundleMon
        continue-on-error: true
        run: npx bundlemon
        env:
          CI_COMMIT_SHA: ${{ env.CI_COMMIT_SHA }}
