name: Screenshot tests

on:
  pull_request:
    paths:
      - 'projects/**'
      - '!projects/*testing/**'
      - '!projects/icons/**'
      - 'angular.json'
      - 'package.json'
      - 'tsconfig*'
      - '**/demo-integrations.yml'
    branches-ignore:
      - 'release/**'
  push:
    branches:
      - '!main'
      - '!release/**'

env:
  NX_BRANCH: ${{ github.event.number }}
  CYPRESS_API_URL: http://localhost:1234/
  SNAPSHOTS_PATH: ./projects/demo-integrations/cypress/snapshots

  # disable shared memory X11 affecting Cypress v4 and Chrome
  # https://github.com/cypress-io/cypress-docker-images/issues/270
  QT_X11_NO_MITSHM: 1
  _X11_NO_MITSHM: 1
  _MITSHM: 0
  DISPLAY: ':99'

jobs:
  demo-integrations:
    name: Cypress
    runs-on: ubuntu-latest
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      CYPRESS_CACHE_FOLDER: ./node_modules/cache-cypress

    services:
      sorry-cypress-director:
        image: agoldis/sorry-cypress-director:2.1
        ports:
          - 1234:1234

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Try rebase locally for check affected e2e
        uses: imba-tjd/rebase-upstream-action@0.5
        with:
          upstream: Tinkoff/taiga-ui
          branch: main
          push: false

      - run: |
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Ignore running parallel Xvfb servers
        run: Xvfb :99 &

      - name: Health check of taiga-ui.dev
        run: curl -X GET -I -f "https://taiga-ui.dev/next"

      - name: Build demo/local application
        run: npm run build:demo

      - name: Serve demo/local application in background
        run: |
          npm run serve:compiled & sleep 5
          curl -X GET -I -f "http://localhost:3333"
      - name: Run screenshot tests on demo/localhost
        run: npm run concurrently "npm run cy2:run:localhost" "sleep 10 && npm run cy2:run:localhost"

      - name: Run screenshot tests on demo/next
        continue-on-error: true
        env:
          CYPRESS_failOnSnapshotDiff: 0 # note: need for collect all diff files for lumberjack bot
        run: npm run concurrently "npm run cy2:run:demo:next" "sleep 10 && npm run cy2:run:demo:next"

      - name: Check if diff-output exists
        id: diff-checker
        run: |
          echo "::set-output name=diff_exist::$(find ${{ env.SNAPSHOTS_PATH }} -type d -name '__diff_output__' | wc -l | sed -e 's/^[[:space:]]*//')"

      - name: Fall with an error if diff-output exists
        if: ${{ steps.diff-checker.outputs.diff_exist != '0' }}
        run: |
          find ${{ env.SNAPSHOTS_PATH }} -type d -name '__diff_output__' -exec echo "{}" \;
          exit 1

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ${{ env.SNAPSHOTS_PATH }}
          if-no-files-found: ignore
          retention-days: 5

concurrency:
  group: demo-integrations-${{ github.head_ref }}
  cancel-in-progress: true
