name: Screenshot tests

on:
    pull_request:
        paths:
            - 'projects/**'
            - '!projects/*testing/**'
            - '!projects/demo/**'
            - '!projects/icons/**'
            - 'angular.json'
            - 'package.json'
            - 'tsconfig*'
    push:
        branches:
            - '!main'
            - '!release/**'

env:
    NX_BRANCH: ${{ github.event.number }}

jobs:
    demo-integrations:
        name: Cypress
        runs-on: ubuntu-20.04
        env:
            NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Run screenshot tests
              uses: cypress-io/github-action@v2
              with:
                  build: npm run build:demo
                  command: npm run demo:integrations:ci

            - name: Upload artifact
              uses: actions/upload-artifact@v1
              if: failure()
              with:
                  name: cypress-screenshots
                  path: projects/demo-integrations/cypress/snapshots
                  retention-days: 7

concurrency:
    group: demo-integrations-${{ github.head_ref }}
    cancel-in-progress: true
