name: Deploy / next

on:
  push:
    branches:
      - main
    paths:
      - 'projects/**'
      - 'angular.json'
      - 'package.json'
      - '**/deploy-next.yml'
  workflow_dispatch:

env:
  NX_BRANCH: ${{ github.event.number }}
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

jobs:
  build-and-deploy:
    name: Next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: npm run build:demo:next

      - name: Deploy next
        uses: JamesIves/github-pages-deploy-action@4.2.5
        with:
          branch: gh-pages
          folder: dist/demo/browser/next
          target-folder: next

concurrency:
  group: deploy-next-${{ github.head_ref }}
  cancel-in-progress: true
