name: ⚙️ Cypress component testing
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cypress:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    name: Component testing result
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.55.16
      - uses: taiga-family/ci/actions/setup/variables@v1.55.16
      - uses: taiga-family/ci/actions/setup/node@v1.55.16
      - run: npx tsc -p projects/demo-cypress/tsconfig.json
      - run: npx nx component-test demo-cypress

concurrency:
  group: e2e-cypress-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
