name: Deploy on PR
on: pull_request
jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: |
                    npm ci
                    npm run build:demo
            -   uses: FirebaseExtended/action-hosting-deploy@v0
                with:
                    repoToken: '${{ secrets.GITHUB_TOKEN }}'
                    firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAIGA_UI }}'
                    projectId: taiga-ui
                    expires: 1d
