name: ⚙️ Validate release tag
on:
  push:
    branches: [main, 'release/*']

jobs:
  validate-tag:
    name: Validate tag
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.36.2
        with:
          fetch-depth: 0

      - uses: taiga-family/ci/actions/setup/node@v1.36.2
        id: nodejs-workspace

      - name: Get last tag
        id: info
        run: echo "tag=$(git tag --list --sort=-authordate --merged | head -n1)" >> $GITHUB_OUTPUT

      - name: Show an error if the tag does not match
        if:
          ${{ steps.nodejs-workspace.outputs.root-package-version != steps.info.outputs.tag &&
          !contains(steps.nodejs-workspace.outputs.root-package-version, '-rc') }}
        run: |
          echo "Version from package.json: ${{ steps.nodejs-workspace.outputs.root-package-version }}"
          echo "Last git tag: ${{ steps.info.outputs.tag }}"
          exit 1

concurrency:
  group: validate-tag-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
